### ISSUE TITLE
User login broken

### ISSUE THREAD

**Issue by devaroop** [tsuru/tsuru-dashboard#118]
User cannot login with error 'you must provide a password to login'

Fix: Change the login post request headers from `application/json` to `application/x-www-form-urlencoded` and encode the params accordingly

**Comment by andrewsmedina** [comment]
I believe that this issue is duplicated of https://github.com/tsuru/tsuru-dashboard/issues/117

tsuru-dashboard from master does not work fine with tsurud from master.

But there is a branch 1.0 that works fine with tsurud master version and this bug is already fixed: https://github.com/tsuru/tsuru-dashboard/blob/tsuru1.0/tsuru_dashboard/auth/views.py#L133
